/*****************************************************************************
* Model: model.qm
* File:  code/usart.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/2/0) .................................................................*/
#include "main.h"

#define BSP_TICKS_PER_SEC 100

void Q_onAssert(char const Q_ROM * const Q_ROM_VAR file, int line){

}

void QF_onStartup(void)
{
	BSP_clockInit();
}
void QK_onIdle(void){}
void QF_onCleanup(void) {}
/*void QF_onClockTick(void) {
    QF_TICK((void *)0);
}*/

enum BlinkySignals {
    TIMEOUT_SIG = Q_USER_SIG,
    MAX_SIG
};

/* @(/1/0) .................................................................*/
typedef struct USARTTag {
/* protected: */
    QActive super;

/* private: */
    QTimeEvt TimeEvt;
} USART;

/* protected: */
static QState USART_initial(USART * const me, QEvt const * const e);
static QState USART_on(USART * const me, QEvt const * const e);
static QState USART_off(USART * const me, QEvt const * const e);

/* @(/1/0) .................................................................*/
/* @(/1/0/1) ...............................................................*/
/* @(/1/0/1/0) */
static QState USART_initial(USART * const me, QEvt const * const e) {
    QTimeEvt_postEvery(
        &me->TimeEvt,
        (QActive *)me,
        BSP_TICKS_PER_SEC/2);
    return Q_TRAN(&USART_on);
}
/* @(/1/0/1/1) .............................................................*/
static QState USART_on(USART * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/0/1/1) */
        case Q_ENTRY_SIG: {
            BSP_ledOn();
            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/0/1/1/0) */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&USART_off);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/* @(/1/0/1/2) .............................................................*/
static QState USART_off(USART * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/0/1/2) */
        case Q_ENTRY_SIG: {
            BSP_ledOff();
            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/0/1/2/0) */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&USART_on);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}


static USART l_usart;
QActive *TASK_USART = &l_usart.super;

static void USART_ctor(void) {
    USART *me = (USART *)TASK_USART;
    QActive_ctor(&me->super, (QStateHandler)&USART_initial);
    QTimeEvt_ctor(&me->TimeEvt, TIMEOUT_SIG);
}
int main() {
    USART_ctor();
	BSP_init();
    QF_init();

    static QEvt const *usart_queueSto[10];
    QActive_start(TASK_USART, 1,
                  usart_queueSto, Q_DIM(usart_queueSto),
                  (void *)0, 1024, (QEvt *)0);
    return QF_run();
}
